services:
  db:
    image: postgres:15-alpine
    container_name: medcore_db
    environment:
      POSTGRES_DB: medcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./gateway/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  redis:
    image: redis:7-alpine
    container_name: medcore_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: medcore_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: medcore_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  admin_auth:
    build:
      context: .
      dockerfile: services/admin_auth/Dockerfile
    container_name: medcore_admin_auth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/admin_auth:/app
    ports:
      - "8001:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SECRET_KEY=django-insecure-shared-medcore-key-12345
    depends_on:
      - db
      - kafka

  patient_auth:
    build:
      context: .
      dockerfile: services/patient_auth/Dockerfile
    container_name: medcore_patient_auth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/patient_auth:/app
    ports:
      - "8002:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SECRET_KEY=django-insecure-shared-medcore-key-12345
    depends_on:
      - db
      - kafka

  profiles:
    build:
      context: .
      dockerfile: services/profiles/Dockerfile
    container_name: medcore_profiles
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/profiles:/app
    ports:
      - "8003:8000"
    environment:
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SECRET_KEY=django-insecure-shared-medcore-key-12345
    depends_on:
      - db
      - redis
      - kafka

  notifications:
    build:
      context: .
      dockerfile: services/notifications/Dockerfile
    container_name: medcore_notifications
    command: python manage.py run_kafka_consumer
    volumes:
      - ./services/notifications:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - kafka

  gateway:
    build:
      context: ./gateway
    container_name: medcore_gateway
    ports:
      - "8000:8000"
    depends_on:
      - admin_auth
      - patient_auth
      - profiles

volumes:
  postgres_data:
