version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medcore_db
    environment:
      POSTGRES_DB: medcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: medcore_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-5vw(^o+xw4=-#dbiji9gj9k#bxbyj3-@=qm5uxwu22ysb4c%fk
      - DB_NAME=medcore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
